### PR TITLE
Derive commonly required traits for `Error`

### PR DESCRIPTION
**Pull request by hannobraun**
I only need `PartialEq`/`Eq`, but figured I'd add other commonly
required traits while I'm at it. I looked at the Rust core library and
just derived all traits that `Option` derives, so I don't think I forgot
anything important.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @hannobraun.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ecf68c7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ecf68c7 with merge ecf68c7...

**Comment by hannobraun** [comment]
No problem, @japaric. Thank you for all your great work!

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nb/builds/277886692?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ecf68c75cdd88ca5e093b91c0cb807bb44ad5d3c to master...

**Pull request merged**
