### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0741dbb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0741dbb with merge 0741dbb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nb/builds/240648609?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0741dbbeb48cea4f470fc8f203b8b182330b0adb to master...

**Pull request merged**
