### PR TITLE
fix warning in block! when the error type is !

### LINKED ISSUE #5: Warnings in block!, if error type is !
I've implemented `embedded_hal::serial::Write` in my code. In my case, errors can only be returned on receive, so `Error` is `!`, as per the recommendation in the documentation.

I've temporarily replaced the code in my old (blocking) write method with this:
```rust
block!(<Self as Write<u8>>::write(self, data))
    .expect("Write operation should never result in error");
```
This results in the following warnings:
```
warning: unreachable expression
   --> src/uart.rs:151:9
    |
151 |         block!(<Self as Write<u8>>::write(self, data))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unreachable_code)] on by default
    = note: this error originates in a macro outside of the current crate

warning: unreachable pattern
   --> src/uart.rs:151:9
    |
151 |         block!(<Self as Write<u8>>::write(self, data))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unreachable_patterns)] on by default
    = note: this error originates in a macro outside of the current crate

```

If I change `Error` to `()`, the warnings disappear.

### PR DESCRIPTION
**Pull request by japaric**
closes #5

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit caac615 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit caac615 with merge 159cf95...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nb/builds/277919061?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 159cf95a3e849fbf4ede3331903f47ea9d00bce7 to master...

**Pull request merged**
