### PR TITLE
apply #7 to the await! macro

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c2415e4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c2415e4 with merge c2415e4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nb/builds/280395053?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c2415e44db65351e0e6380548d4a998de25b4f1b to master...

**Pull request merged**
