### PR TITLE
feature gate try_nb! and await!; run doc tests

### LINKED ISSUE #9: Release on crates.io
What's currently blocking the release of this crate on [crates.io](https://crates.io/)?

### PR DESCRIPTION
**Pull request by japaric**
in preparation for the v0.1.0 release

closes #9
cc @hannobraun

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6a720b7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6a720b73fdaf1aec8fe11f64f03f107c21f7cb10 with merge b07c06e43132faaae0ee2553ce28109b1d297ed1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nb/builds/326100586?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b07c06e43132faaae0ee2553ce28109b1d297ed1 to master...

**Comment by hannobraun** [comment]
This is great, thank you @japaric! Looking forward to the release.

**Pull request merged**
